version: "3.8"

services:
  fastapi-app:
    build: .
    container_name: fastapi_app
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    volumes: 
      - .:/code
      - ./.env:/code/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: fastapi_database
    restart: always
    ports: 
      - "5432:5432"
    env_file:
      - ./postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fastapi_pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    env_file:
      - ./pgadmin.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin-data:
